import '../../models/event_model.dart';
import '../../models/venue_model.dart';
import '../../models/user_model.dart';
import '../../models/booking_model.dart';
import '../../models/ticket_model.dart';

class MockData {
  // â”€â”€â”€ VENUES â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  static final List<VenueModel> venues = [
    VenueModel(
      id: 'v1',
      name: 'Madison Square Garden',
      city: 'New York',
      address: '4 Pennsylvania Plaza, New York, NY 10001',
      capacity: 20000,
      imageUrl: 'assets/images/venue_madison_sg.jpg',
      rows: 10,
      seatsPerRow: 12,
    ),
    VenueModel(
      id: 'v2',
      name: 'The O2 Arena',
      city: 'London',
      address: 'Peninsula Square, London SE10 0DX',
      capacity: 20000,
      imageUrl: 'assets/images/venue_o2_arena.jpg',
      rows: 10,
      seatsPerRow: 12,
    ),
    VenueModel(
      id: 'v3',
      name: 'Staples Center',
      city: 'Los Angeles',
      address: '1111 S Figueroa St, Los Angeles, CA 90015',
      capacity: 21000,
      imageUrl: 'assets/images/venue_staples_center.jpg',
      rows: 8,
      seatsPerRow: 10,
    ),
    VenueModel(
      id: 'v4',
      name: 'Wembley Stadium',
      city: 'London',
      address: 'London HA9 0WS, United Kingdom',
      capacity: 90000,
      imageUrl: 'assets/images/venue_wembley.jpg',
      rows: 12,
      seatsPerRow: 14,
    ),
    VenueModel(
      id: 'v5',
      name: 'Sydney Opera House',
      city: 'Sydney',
      address: 'Bennelong Point, Sydney NSW 2000',
      capacity: 5738,
      imageUrl: 'assets/images/venue_sydney_opera.jpg',
      rows: 8,
      seatsPerRow: 10,
    ),
    VenueModel(
      id: 'v6',
      name: 'Red Rocks Amphitheatre',
      city: 'Denver',
      address: '18300 W Alameda Pkwy, Morrison, CO 80465',
      capacity: 9525,
      imageUrl: 'assets/images/venue_red_rocks.jpg',
      rows: 10,
      seatsPerRow: 12,
    ),
  ];

  // â”€â”€â”€ EVENTS â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  static final List<EventModel> events = [
    EventModel(
      id: 'e1',
      title: 'Taylor Swift - Eras Tour',
      imageUrl: 'assets/images/event_taylor_swift.jpg',
      category: 'Concerts',
      date: DateTime(2026, 3, 15),
      time: '7:00 PM',
      venueId: 'v1',
      venueName: 'Madison Square Garden',
      city: 'New York',
      artists: ['Taylor Swift'],
      description:
          'Experience the magic of Taylor Swift\'s record-breaking Eras Tour! A spectacular journey through her musical history featuring songs from every album. An unforgettable night of music, visuals, and pure artistry.',
      ticketTiers: [
        TicketTier(name: 'General', price: 89.99, totalQuantity: 5000, soldQuantity: 4200),
        TicketTier(name: 'VIP', price: 249.99, totalQuantity: 1000, soldQuantity: 850),
        TicketTier(name: 'Platinum', price: 499.99, totalQuantity: 200, soldQuantity: 150),
      ],
      isFeatured: true,
      isTrending: true,
      rating: 4.9,
      reviewCount: 2450,
    ),
    EventModel(
      id: 'e2',
      title: 'Coldplay - Music of the Spheres',
      imageUrl: 'assets/images/event_coldplay.jpg',
      category: 'Concerts',
      date: DateTime(2026, 3, 22),
      time: '8:00 PM',
      venueId: 'v4',
      venueName: 'Wembley Stadium',
      city: 'London',
      artists: ['Coldplay'],
      description:
          'Coldplay brings their spectacular Music of the Spheres World Tour to Wembley Stadium. Featuring their greatest hits alongside new material, with stunning visual effects and LED wristbands for every attendee.',
      ticketTiers: [
        TicketTier(name: 'General', price: 75.00, totalQuantity: 30000, soldQuantity: 28000),
        TicketTier(name: 'VIP', price: 199.99, totalQuantity: 5000, soldQuantity: 4600),
        TicketTier(name: 'Platinum', price: 399.99, totalQuantity: 500, soldQuantity: 400),
      ],
      isFeatured: true,
      isTrending: true,
      rating: 4.8,
      reviewCount: 1890,
    ),
    EventModel(
      id: 'e3',
      title: 'NBA Finals - Game 7',
      imageUrl: 'assets/images/event_nba_finals.jpg',
      category: 'Sports',
      date: DateTime(2026, 6, 18),
      time: '9:00 PM',
      venueId: 'v3',
      venueName: 'Staples Center',
      city: 'Los Angeles',
      artists: ['Lakers vs Celtics'],
      description:
          'The ultimate showdown! Watch the NBA Finals Game 7 live at the Staples Center. Two legendary teams battle it out for the championship in what promises to be an electrifying night of basketball.',
      ticketTiers: [
        TicketTier(name: 'Upper Level', price: 150.00, totalQuantity: 8000, soldQuantity: 7800),
        TicketTier(name: 'Lower Level', price: 350.00, totalQuantity: 3000, soldQuantity: 2900),
        TicketTier(name: 'Courtside', price: 1200.00, totalQuantity: 100, soldQuantity: 95),
      ],
      isFeatured: true,
      isTrending: true,
      rating: 4.7,
      reviewCount: 890,
      status: 'Active',
    ),
    EventModel(
      id: 'e4',
      title: 'Hamilton - Musical',
      imageUrl: 'assets/images/event_hamilton.jpg',
      category: 'Theatre',
      date: DateTime(2026, 4, 5),
      time: '2:00 PM',
      venueId: 'v5',
      venueName: 'Sydney Opera House',
      city: 'Sydney',
      artists: ['Lin-Manuel Miranda Production'],
      description:
          'The revolutionary musical that took the world by storm. Hamilton tells the story of America\'s founding father Alexander Hamilton through hip-hop, R&B, and traditional show tunes.',
      ticketTiers: [
        TicketTier(name: 'Balcony', price: 65.00, totalQuantity: 2000, soldQuantity: 1800),
        TicketTier(name: 'Orchestra', price: 145.00, totalQuantity: 1000, soldQuantity: 920),
        TicketTier(name: 'Premium', price: 275.00, totalQuantity: 300, soldQuantity: 280),
      ],
      isFeatured: false,
      isTrending: true,
      rating: 4.9,
      reviewCount: 3200,
    ),
    EventModel(
      id: 'e5',
      title: 'Dave Chappelle - Live',
      imageUrl: 'assets/images/event_dave_chappelle.jpg',
      category: 'Comedy',
      date: DateTime(2026, 3, 28),
      time: '9:30 PM',
      venueId: 'v6',
      venueName: 'Red Rocks Amphitheatre',
      city: 'Denver',
      artists: ['Dave Chappelle'],
      description:
          'The legendary Dave Chappelle brings his iconic stand-up comedy to the breathtaking Red Rocks Amphitheatre. An intimate evening of sharp wit, storytelling, and unforgettable laughs under the stars.',
      ticketTiers: [
        TicketTier(name: 'General Admission', price: 95.00, totalQuantity: 5000, soldQuantity: 4500),
        TicketTier(name: 'Reserved', price: 175.00, totalQuantity: 1500, soldQuantity: 1300),
      ],
      isFeatured: false,
      isTrending: false,
      rating: 4.6,
      reviewCount: 670,
    ),
    EventModel(
      id: 'e6',
      title: 'Coachella Music Festival 2026',
      imageUrl: 'assets/images/event_coachella.jpg',
      category: 'Festivals',
      date: DateTime(2026, 4, 10),
      time: '12:00 PM',
      venueId: 'v6',
      venueName: 'Empire Polo Club',
      city: 'Indio',
      artists: ['Bad Bunny', 'Billie Eilish', 'Frank Ocean', 'BLACKPINK'],
      description:
          'The world\'s most iconic music festival returns! Three days of incredible performances across multiple stages, immersive art installations, and unforgettable experiences in the California desert.',
      ticketTiers: [
        TicketTier(name: 'GA Pass', price: 449.00, totalQuantity: 50000, soldQuantity: 48000),
        TicketTier(name: 'VIP Pass', price: 999.00, totalQuantity: 5000, soldQuantity: 4800),
        TicketTier(name: 'Safari Camping', price: 2500.00, totalQuantity: 200, soldQuantity: 200),
      ],
      isFeatured: true,
      isTrending: true,
      rating: 4.8,
      reviewCount: 5600,
    ),
    EventModel(
      id: 'e7',
      title: 'Disney on Ice - Frozen',
      imageUrl: 'assets/images/event_disney_on_ice.jpg',
      category: 'Family',
      date: DateTime(2026, 5, 1),
      time: '3:00 PM',
      venueId: 'v1',
      venueName: 'Madison Square Garden',
      city: 'New York',
      artists: ['Disney Performers'],
      description:
          'Let it go! Join Anna, Elsa, Olaf, and the gang in this magical ice skating spectacular. A family-friendly show that brings the beloved Frozen story to life on ice with stunning costumes and choreography.',
      ticketTiers: [
        TicketTier(name: 'Standard', price: 45.00, totalQuantity: 10000, soldQuantity: 7500),
        TicketTier(name: 'Premium', price: 85.00, totalQuantity: 3000, soldQuantity: 2200),
        TicketTier(name: 'Front Row', price: 145.00, totalQuantity: 500, soldQuantity: 350),
      ],
      isFeatured: false,
      isTrending: false,
      rating: 4.5,
      reviewCount: 1200,
    ),
    EventModel(
      id: 'e8',
      title: 'UFC 300 - Championship Night',
      imageUrl: 'assets/images/event_ufc.jpg',
      category: 'Sports',
      date: DateTime(2026, 4, 20),
      time: '10:00 PM',
      venueId: 'v3',
      venueName: 'Staples Center',
      city: 'Los Angeles',
      artists: ['Main Event TBA'],
      description:
          'UFC 300 promises to be the biggest MMA event in history! Multiple championship bouts headline this historic milestone card featuring the best fighters on the planet.',
      ticketTiers: [
        TicketTier(name: 'General', price: 200.00, totalQuantity: 8000, soldQuantity: 7600),
        TicketTier(name: 'Gold', price: 500.00, totalQuantity: 2000, soldQuantity: 1900),
        TicketTier(name: 'Cageside', price: 1500.00, totalQuantity: 100, soldQuantity: 90),
      ],
      isFeatured: false,
      isTrending: true,
      rating: 4.7,
      reviewCount: 980,
    ),
    EventModel(
      id: 'e9',
      title: 'Ed Sheeran - Mathematics Tour',
      imageUrl: 'assets/images/event_ed_sheeran.jpg',
      category: 'Concerts',
      date: DateTime(2026, 5, 15),
      time: '7:30 PM',
      venueId: 'v2',
      venueName: 'The O2 Arena',
      city: 'London',
      artists: ['Ed Sheeran'],
      description:
          'Ed Sheeran\'s Mathematics Tour comes to The O2 Arena. Experience the singer-songwriter\'s incredible one-man show with his loop pedal magic, performing chart-topping hits in an intimate yet grand setting.',
      ticketTiers: [
        TicketTier(name: 'General', price: 70.00, totalQuantity: 8000, soldQuantity: 7200),
        TicketTier(name: 'VIP', price: 180.00, totalQuantity: 2000, soldQuantity: 1800),
        TicketTier(name: 'Platinum', price: 350.00, totalQuantity: 300, soldQuantity: 250),
      ],
      isFeatured: false,
      isTrending: false,
      rating: 4.8,
      reviewCount: 2100,
    ),
    EventModel(
      id: 'e10',
      title: 'Trevor Noah - Off the Record',
      imageUrl: 'assets/images/event_trevor_noah.jpg',
      category: 'Comedy',
      date: DateTime(2026, 3, 30),
      time: '8:00 PM',
      venueId: 'v5',
      venueName: 'Sydney Opera House',
      city: 'Sydney',
      artists: ['Trevor Noah'],
      description:
          'Former Daily Show host Trevor Noah brings his sharp, globally-inspired comedy to Sydney. A masterful blend of cultural commentary, personal anecdotes, and razor-sharp observations.',
      ticketTiers: [
        TicketTier(name: 'Standard', price: 55.00, totalQuantity: 3000, soldQuantity: 2700),
        TicketTier(name: 'Premium', price: 120.00, totalQuantity: 800, soldQuantity: 720),
      ],
      isFeatured: false,
      isTrending: false,
      rating: 4.6,
      reviewCount: 540,
    ),
    EventModel(
      id: 'e11',
      title: 'Wimbledon Finals 2026',
      imageUrl: 'assets/images/event_wimbledon.jpg',
      category: 'Sports',
      date: DateTime(2026, 7, 12),
      time: '2:00 PM',
      venueId: 'v2',
      venueName: 'All England Club',
      city: 'London',
      artists: ['TBA Finalists'],
      description:
          'The most prestigious tennis tournament in the world. Watch the Men\'s Singles Final at the legendary Centre Court with its retractable roof and perfectly manicured grass courts.',
      ticketTiers: [
        TicketTier(name: 'Grounds Pass', price: 120.00, totalQuantity: 15000, soldQuantity: 14500),
        TicketTier(name: 'Court Seat', price: 380.00, totalQuantity: 5000, soldQuantity: 4900),
        TicketTier(name: 'Debenture', price: 850.00, totalQuantity: 500, soldQuantity: 480),
      ],
      isFeatured: false,
      isTrending: true,
      rating: 4.9,
      reviewCount: 1550,
    ),
    EventModel(
      id: 'e12',
      title: 'The Lion King - Broadway',
      imageUrl: 'assets/images/event_lion_king.jpg',
      category: 'Theatre',
      date: DateTime(2026, 4, 15),
      time: '7:30 PM',
      venueId: 'v1',
      venueName: 'Minskoff Theatre',
      city: 'New York',
      artists: ['Broadway Cast'],
      description:
          'The award-winning musical adapted from the Disney animated classic. Stunning puppetry, breathtaking costumes, and unforgettable music by Elton John and Tim Rice make this a must-see theatrical experience.',
      ticketTiers: [
        TicketTier(name: 'Rear Mezzanine', price: 79.00, totalQuantity: 800, soldQuantity: 600),
        TicketTier(name: 'Orchestra', price: 179.00, totalQuantity: 500, soldQuantity: 430),
        TicketTier(name: 'Premium Orchestra', price: 299.00, totalQuantity: 150, soldQuantity: 120),
      ],
      isFeatured: false,
      isTrending: false,
      rating: 4.8,
      reviewCount: 4200,
    ),
    EventModel(
      id: 'e14',
      title: 'Weekend Jazz in the Park',
      imageUrl: 'assets/images/event_hamilton.jpg',
      category: 'Concerts',
      date: DateTime(2026, 3, 7),
      time: '4:00 PM',
      venueId: 'v6',
      venueName: 'Red Rocks Amphitheatre',
      city: 'Denver',
      artists: ['Miles Davis Ensemble', 'Norah Jones'],
      description:
          'A relaxed outdoor jazz afternoon at the iconic Red Rocks. Bring your friends, grab a blanket, and enjoy soulful jazz performances as the sun sets over the stunning Colorado rock formations.',
      ticketTiers: [
        TicketTier(name: 'General', price: 35.00, totalQuantity: 3000, soldQuantity: 1200),
        TicketTier(name: 'Reserved', price: 65.00, totalQuantity: 800, soldQuantity: 300),
      ],
      isFeatured: false,
      isTrending: true,
      rating: 4.5,
      reviewCount: 210,
    ),
    EventModel(
      id: 'e15',
      title: 'Sunday Comedy Showcase',
      imageUrl: 'assets/images/event_trevor_noah.jpg',
      category: 'Comedy',
      date: DateTime(2026, 3, 8),
      time: '7:00 PM',
      venueId: 'v1',
      venueName: 'Madison Square Garden',
      city: 'New York',
      artists: ['Chris Rock', 'Ali Wong', 'Kevin Hart'],
      description:
          'Three comedy legends take the stage for one epic Sunday night showcase. Expect non-stop laughter with world-class stand-up from some of the biggest names in comedy.',
      ticketTiers: [
        TicketTier(name: 'General', price: 55.00, totalQuantity: 5000, soldQuantity: 3800),
        TicketTier(name: 'VIP', price: 120.00, totalQuantity: 1000, soldQuantity: 750),
      ],
      isFeatured: false,
      isTrending: true,
      rating: 4.7,
      reviewCount: 430,
    ),
    EventModel(
      id: 'e16',
      title: 'MLS All-Star Game',
      imageUrl: 'assets/images/event_nba_finals.jpg',
      category: 'Sports',
      date: DateTime(2026, 3, 7),
      time: '5:30 PM',
      venueId: 'v3',
      venueName: 'Staples Center',
      city: 'Los Angeles',
      artists: ['MLS East vs MLS West'],
      description:
          'The best players in Major League Soccer face off in the annual All-Star showdown. A showcase of skill, speed, and celebration of the beautiful game in the heart of Los Angeles.',
      ticketTiers: [
        TicketTier(name: 'Upper Tier', price: 45.00, totalQuantity: 6000, soldQuantity: 4200),
        TicketTier(name: 'Lower Tier', price: 95.00, totalQuantity: 2000, soldQuantity: 1500),
        TicketTier(name: 'Pitch Side', price: 250.00, totalQuantity: 300, soldQuantity: 200),
      ],
      isFeatured: false,
      isTrending: false,
      rating: 4.4,
      reviewCount: 320,
    ),
    EventModel(
      id: 'e13',
      title: 'Electric Daisy Carnival',
      imageUrl: 'assets/images/event_edc.jpg',
      category: 'Festivals',
      date: DateTime(2026, 5, 22),
      time: '5:00 PM',
      venueId: 'v3',
      venueName: 'Las Vegas Motor Speedway',
      city: 'Las Vegas',
      artists: ['Tiësto', 'Martin Garrix', 'Zedd', 'Marshmello'],
      description:
          'The world\'s largest dance music festival transforms the Las Vegas Motor Speedway into a neon wonderland. Three nights of electronic music across 8 stages with carnival rides and art installations.',
      ticketTiers: [
        TicketTier(name: '3-Day GA', price: 369.00, totalQuantity: 80000, soldQuantity: 75000),
        TicketTier(name: '3-Day VIP', price: 799.00, totalQuantity: 10000, soldQuantity: 9200),
        TicketTier(name: 'Bottle Service', price: 3000.00, totalQuantity: 100, soldQuantity: 85),
      ],
      isFeatured: true,
      isTrending: false,
      rating: 4.7,
      reviewCount: 3400,
    ),

    // ── Las Vegas extra events ─────────────────────────────────
    EventModel(
      id: 'e17',
      title: 'Bruno Mars - Live at Dolby Live',
      imageUrl: 'assets/images/event_taylor_swift.jpg',
      category: 'Concerts',
      date: DateTime(2026, 4, 12),
      time: '9:00 PM',
      venueId: 'v3',
      venueName: 'Dolby Live at Park MGM',
      city: 'Las Vegas',
      artists: ['Bruno Mars'],
      description:
          'Bruno Mars brings his electrifying residency back to Dolby Live. Expect a high-energy night packed with his greatest hits, showman choreography, and an intimate venue vibe unlike any arena show.',
      ticketTiers: [
        TicketTier(name: 'Floor', price: 189.00, totalQuantity: 2000, soldQuantity: 1800),
        TicketTier(name: 'Reserved', price: 299.00, totalQuantity: 1000, soldQuantity: 850),
        TicketTier(name: 'VIP Table', price: 699.00, totalQuantity: 100, soldQuantity: 80),
      ],
      isFeatured: true,
      isTrending: true,
      rating: 4.9,
      reviewCount: 3100,
    ),
    EventModel(
      id: 'e18',
      title: 'Tyson vs Jones - Boxing Night',
      imageUrl: 'assets/images/event_ufc.jpg',
      category: 'Sports',
      date: DateTime(2026, 6, 6),
      time: '8:00 PM',
      venueId: 'v3',
      venueName: 'T-Mobile Arena',
      city: 'Las Vegas',
      artists: ['Mike Tyson', 'Roy Jones Jr.'],
      description:
          'Two boxing legends step back into the ring at T-Mobile Arena for a highly anticipated rematch. An unmissable night of world-class boxing in the entertainment capital of the world.',
      ticketTiers: [
        TicketTier(name: 'Upper Bowl', price: 120.00, totalQuantity: 6000, soldQuantity: 5500),
        TicketTier(name: 'Lower Bowl', price: 280.00, totalQuantity: 3000, soldQuantity: 2700),
        TicketTier(name: 'Ringside', price: 1200.00, totalQuantity: 200, soldQuantity: 180),
      ],
      isFeatured: false,
      isTrending: true,
      rating: 4.6,
      reviewCount: 870,
    ),
    EventModel(
      id: 'e19',
      title: 'Cirque du Soleil - O',
      imageUrl: 'assets/images/event_hamilton.jpg',
      category: 'Theatre',
      date: DateTime(2026, 3, 20),
      time: '7:30 PM',
      venueId: 'v3',
      venueName: 'Bellagio Theatre',
      city: 'Las Vegas',
      artists: ['Cirque du Soleil Company'],
      description:
          'The iconic Cirque du Soleil water spectacle at the Bellagio. Acrobats, synchronized swimmers, and divers perform over and in a 1.5 million gallon pool in this breathtaking theatrical masterpiece.',
      ticketTiers: [
        TicketTier(name: 'Category C', price: 115.00, totalQuantity: 1500, soldQuantity: 1300),
        TicketTier(name: 'Category B', price: 175.00, totalQuantity: 800, soldQuantity: 720),
        TicketTier(name: 'Category A', price: 235.00, totalQuantity: 300, soldQuantity: 260),
      ],
      isFeatured: false,
      isTrending: false,
      rating: 4.8,
      reviewCount: 5800,
    ),

    // ── Indio extra events ─────────────────────────────────────
    EventModel(
      id: 'e20',
      title: 'Stagecoach Country Music Fest',
      imageUrl: 'assets/images/event_edc.jpg',
      category: 'Festivals',
      date: DateTime(2026, 4, 24),
      time: '1:00 PM',
      venueId: 'v3',
      venueName: 'Empire Polo Club',
      city: 'Indio',
      artists: ['Morgan Wallen', 'Luke Bryan', 'Carrie Underwood'],
      description:
          'America\'s biggest country music festival returns to the Empire Polo Club. Three days of stellar country performances, line dancing, barrel riding, and good old-fashioned fun in the California desert.',
      ticketTiers: [
        TicketTier(name: '3-Day GA', price: 329.00, totalQuantity: 40000, soldQuantity: 36000),
        TicketTier(name: '3-Day VIP', price: 749.00, totalQuantity: 4000, soldQuantity: 3600),
        TicketTier(name: 'Camping Pass', price: 1199.00, totalQuantity: 500, soldQuantity: 450),
      ],
      isFeatured: true,
      isTrending: true,
      rating: 4.7,
      reviewCount: 4200,
    ),
    EventModel(
      id: 'e21',
      title: 'Desert Nights Comedy Bash',
      imageUrl: 'assets/images/event_dave_chappelle.jpg',
      category: 'Comedy',
      date: DateTime(2026, 5, 9),
      time: '8:30 PM',
      venueId: 'v3',
      venueName: 'Indio Amphitheater',
      city: 'Indio',
      artists: ['Ali Wong', 'Hasan Minhaj', 'Gabriel Iglesias'],
      description:
          'Three comedy superstars bring laughs to the Indio Amphitheater under the open desert sky. An evening of world-class stand-up with a warm Coachella Valley breeze and unforgettable punchlines.',
      ticketTiers: [
        TicketTier(name: 'General Admission', price: 65.00, totalQuantity: 3500, soldQuantity: 2800),
        TicketTier(name: 'Reserved', price: 110.00, totalQuantity: 1000, soldQuantity: 800),
        TicketTier(name: 'Backstage Meet & Greet', price: 299.00, totalQuantity: 50, soldQuantity: 40),
      ],
      isFeatured: false,
      isTrending: true,
      rating: 4.5,
      reviewCount: 620,
    ),
    EventModel(
      id: 'e22',
      title: 'Desert Bloom Music & Arts',
      imageUrl: 'assets/images/event_coachella.jpg',
      category: 'Festivals',
      date: DateTime(2026, 3, 14),
      time: '11:00 AM',
      venueId: 'v3',
      venueName: 'Polo Grounds',
      city: 'Indio',
      artists: ['SZA', 'Childish Gambino', 'Tame Impala'],
      description:
          'A boutique arts and music festival celebrating the blooming of the desert. Intimate stages, immersive art installations, gourmet food vendors, and a lineup of indie and alternative artists.',
      ticketTiers: [
        TicketTier(name: 'Day Pass', price: 89.00, totalQuantity: 10000, soldQuantity: 7500),
        TicketTier(name: 'Weekend Pass', price: 199.00, totalQuantity: 5000, soldQuantity: 4200),
        TicketTier(name: 'VIP Weekend', price: 449.00, totalQuantity: 500, soldQuantity: 380),
      ],
      isFeatured: false,
      isTrending: false,
      rating: 4.4,
      reviewCount: 1100,
    ),

    // ── Sydney extra events ────────────────────────────────────
    EventModel(
      id: 'e23',
      title: 'Sydney Mardi Gras Spectacular',
      imageUrl: 'assets/images/event_coachella.jpg',
      category: 'Festivals',
      date: DateTime(2026, 3, 7),
      time: '7:00 PM',
      venueId: 'v5',
      venueName: 'Sydney Showground',
      city: 'Sydney',
      artists: ['Kylie Minogue', 'Sam Smith', 'Years & Years'],
      description:
          'The world-famous Sydney Gay & Lesbian Mardi Gras Party — one of the most inclusive and spectacular celebrations on the planet. World-class DJs, dazzling performances, and a night to remember.',
      ticketTiers: [
        TicketTier(name: 'General', price: 90.00, totalQuantity: 15000, soldQuantity: 14200),
        TicketTier(name: 'VIP', price: 220.00, totalQuantity: 2000, soldQuantity: 1800),
      ],
      isFeatured: false,
      isTrending: true,
      rating: 4.7,
      reviewCount: 2300,
    ),
    EventModel(
      id: 'e24',
      title: 'Rugby World Cup Final',
      imageUrl: 'assets/images/event_nba_finals.jpg',
      category: 'Sports',
      date: DateTime(2026, 6, 27),
      time: '5:00 PM',
      venueId: 'v5',
      venueName: 'Stadium Australia',
      city: 'Sydney',
      artists: ['TBA Finalists'],
      description:
          'The pinnacle of rugby union — the Rugby World Cup Final live at Stadium Australia. An 80,000-strong crowd witnesses the crowning of the world\'s best rugby nation in this iconic Sydney venue.',
      ticketTiers: [
        TicketTier(name: 'Upper Tier', price: 95.00, totalQuantity: 30000, soldQuantity: 28000),
        TicketTier(name: 'Lower Tier', price: 195.00, totalQuantity: 10000, soldQuantity: 9600),
        TicketTier(name: 'Platinum', price: 450.00, totalQuantity: 1000, soldQuantity: 950),
      ],
      isFeatured: false,
      isTrending: true,
      rating: 4.8,
      reviewCount: 1600,
    ),

    // ── Denver extra events ────────────────────────────────────
    EventModel(
      id: 'e25',
      title: 'Michael Bublé - Live in Concert',
      imageUrl: 'assets/images/event_ed_sheeran.jpg',
      category: 'Concerts',
      date: DateTime(2026, 4, 18),
      time: '7:30 PM',
      venueId: 'v6',
      venueName: 'Ball Arena',
      city: 'Denver',
      artists: ['Michael Bublé'],
      description:
          'The smooth-voiced crooner Michael Bublé brings his timeless classics and jazz standards to Denver\'s Ball Arena. An elegant evening of swing, soul, and spectacular showmanship for all ages.',
      ticketTiers: [
        TicketTier(name: 'Upper Level', price: 55.00, totalQuantity: 6000, soldQuantity: 4800),
        TicketTier(name: 'Lower Level', price: 115.00, totalQuantity: 3000, soldQuantity: 2600),
        TicketTier(name: 'Floor Pit', price: 185.00, totalQuantity: 1000, soldQuantity: 880),
      ],
      isFeatured: false,
      isTrending: false,
      rating: 4.7,
      reviewCount: 1450,
    ),
    EventModel(
      id: 'e26',
      title: 'Denver Food & Wine Classic',
      imageUrl: 'assets/images/event_hamilton.jpg',
      category: 'Festivals',
      date: DateTime(2026, 6, 13),
      time: '12:00 PM',
      venueId: 'v6',
      venueName: 'Civic Center Park',
      city: 'Denver',
      artists: ['Top Colorado Chefs', 'International Sommeliers'],
      description:
          'Colorado\'s premier food and wine celebration returns to Civic Center Park. Taste creations from 60+ award-winning restaurants, explore curated wine and craft beer selections amid the stunning Rocky Mountain backdrop.',
      ticketTiers: [
        TicketTier(name: 'Tasting Pass', price: 79.00, totalQuantity: 5000, soldQuantity: 3200),
        TicketTier(name: 'Grand Tasting', price: 145.00, totalQuantity: 2000, soldQuantity: 1400),
        TicketTier(name: 'Chef\'s Table', price: 395.00, totalQuantity: 100, soldQuantity: 65),
      ],
      isFeatured: false,
      isTrending: false,
      rating: 4.6,
      reviewCount: 780,
    ),
  ];

  // â”€â”€â”€ USERS â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  static final List<UserModel> users = [
    UserModel(
      id: 'u1',
      fullName: 'Admin User',
      email: 'admin@app.com',
      phone: '+1 555-0100',
      avatarUrl: 'assets/images/avatar_admin.jpg',
      isAdmin: true,
      joinDate: DateTime(2024, 1, 1),
      bookingCount: 5,
    ),
    UserModel(
      id: 'u2',
      fullName: 'John Doe',
      email: 'john@example.com',
      phone: '+1 555-0101',
      avatarUrl: 'assets/images/avatar_john.jpg',
      joinDate: DateTime(2024, 6, 15),
      bookingCount: 12,
    ),
    UserModel(
      id: 'u3',
      fullName: 'Sarah Connor',
      email: 'sarah@example.com',
      phone: '+1 555-0102',
      avatarUrl: 'assets/images/avatar_sarah.jpg',
      joinDate: DateTime(2024, 8, 22),
      bookingCount: 8,
    ),
    UserModel(
      id: 'u4',
      fullName: 'Mike Johnson',
      email: 'mike@example.com',
      phone: '+1 555-0103',
      avatarUrl: 'assets/images/avatar_mike.jpg',
      joinDate: DateTime(2025, 1, 10),
      bookingCount: 3,
    ),
    UserModel(
      id: 'u5',
      fullName: 'Emily Davis',
      email: 'emily@example.com',
      phone: '+1 555-0104',
      avatarUrl: 'assets/images/avatar_emily.jpg',
      joinDate: DateTime(2025, 2, 28),
      bookingCount: 15,
    ),
    UserModel(
      id: 'u6',
      fullName: 'Carlos Rodriguez',
      email: 'carlos@example.com',
      phone: '+1 555-0105',
      avatarUrl: 'assets/images/avatar_carlos.jpg',
      joinDate: DateTime(2025, 3, 5),
      bookingCount: 6,
    ),
    UserModel(
      id: 'u7',
      fullName: 'Aisha Patel',
      email: 'aisha@example.com',
      phone: '+44 7700-900123',
      avatarUrl: 'assets/images/avatar_aisha.jpg',
      joinDate: DateTime(2025, 4, 12),
      bookingCount: 9,
    ),
    UserModel(
      id: 'u8',
      fullName: 'James Wilson',
      email: 'james@example.com',
      phone: '+1 555-0106',
      avatarUrl: 'assets/images/avatar_james.jpg',
      joinDate: DateTime(2025, 5, 20),
      bookingCount: 2,
    ),
    UserModel(
      id: 'u9',
      fullName: 'Luna Kim',
      email: 'luna@example.com',
      phone: '+82 10-1234-5678',
      avatarUrl: 'assets/images/avatar_luna.jpg',
      joinDate: DateTime(2025, 7, 1),
      bookingCount: 11,
    ),
    UserModel(
      id: 'u10',
      fullName: 'David Brown',
      email: 'david@example.com',
      phone: '+1 555-0107',
      avatarUrl: 'assets/images/avatar_david.jpg',
      joinDate: DateTime(2025, 8, 15),
      bookingCount: 4,
    ),
  ];

  // â”€â”€â”€ BOOKINGS â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  static final List<BookingModel> bookings = [
    BookingModel(
      id: 'b1',
      userId: 'u2',
      userName: 'John Doe',
      userEmail: 'john@example.com',
      eventId: 'e1',
      eventTitle: 'Taylor Swift - Eras Tour',
      eventImageUrl: 'assets/images/event_taylor_swift.jpg',
      venue: 'Madison Square Garden',
      eventDate: DateTime(2026, 3, 15),
      tierName: 'VIP',
      seats: ['A5', 'A6'],
      subtotal: 499.98,
      serviceFee: 50.00,
      discount: 0,
      total: 549.98,
      paymentMethod: 'Credit Card',
      bookingDate: DateTime(2025, 12, 1),
      status: BookingStatus.confirmed,
      qrData: 'EVT-B1-TS2026-VIP-A5A6',
    ),
    BookingModel(
      id: 'b2',
      userId: 'u3',
      userName: 'Sarah Connor',
      userEmail: 'sarah@example.com',
      eventId: 'e2',
      eventTitle: 'Coldplay - Music of the Spheres',
      eventImageUrl: 'assets/images/event_coldplay.jpg',
      venue: 'Wembley Stadium',
      eventDate: DateTime(2026, 3, 22),
      tierName: 'General',
      seats: ['D2', 'D3', 'D4'],
      subtotal: 225.00,
      serviceFee: 22.50,
      discount: 22.50,
      total: 225.00,
      promoCode: 'SAVE10',
      paymentMethod: 'UPI',
      bookingDate: DateTime(2025, 11, 15),
      status: BookingStatus.confirmed,
      qrData: 'EVT-B2-CP2026-GEN-D2D3D4',
    ),
    BookingModel(
      id: 'b3',
      userId: 'u4',
      userName: 'Mike Johnson',
      userEmail: 'mike@example.com',
      eventId: 'e3',
      eventTitle: 'NBA Finals - Game 7',
      eventImageUrl: 'assets/images/event_nba_finals.jpg',
      venue: 'Staples Center',
      eventDate: DateTime(2026, 6, 18),
      tierName: 'Lower Level',
      seats: ['B8'],
      subtotal: 350.00,
      serviceFee: 35.00,
      discount: 0,
      total: 385.00,
      paymentMethod: 'Net Banking',
      bookingDate: DateTime(2026, 1, 5),
      status: BookingStatus.confirmed,
      qrData: 'EVT-B3-NBA2026-LL-B8',
    ),
    BookingModel(
      id: 'b4',
      userId: 'u5',
      userName: 'Emily Davis',
      userEmail: 'emily@example.com',
      eventId: 'e4',
      eventTitle: 'Hamilton - Musical',
      eventImageUrl: 'assets/images/event_hamilton.jpg',
      venue: 'Sydney Opera House',
      eventDate: DateTime(2026, 4, 5),
      tierName: 'Orchestra',
      seats: ['C3', 'C4'],
      subtotal: 290.00,
      serviceFee: 29.00,
      discount: 0,
      total: 319.00,
      paymentMethod: 'Credit Card',
      bookingDate: DateTime(2025, 12, 20),
      status: BookingStatus.confirmed,
      qrData: 'EVT-B4-HAM2026-ORC-C3C4',
    ),
    BookingModel(
      id: 'b5',
      userId: 'u2',
      userName: 'John Doe',
      userEmail: 'john@example.com',
      eventId: 'e5',
      eventTitle: 'Dave Chappelle - Live',
      eventImageUrl: 'assets/images/event_dave_chappelle.jpg',
      venue: 'Red Rocks Amphitheatre',
      eventDate: DateTime(2026, 3, 28),
      tierName: 'Reserved',
      seats: ['E1', 'E2'],
      subtotal: 350.00,
      serviceFee: 35.00,
      discount: 35.00,
      total: 350.00,
      promoCode: 'SAVE10',
      paymentMethod: 'Wallet',
      bookingDate: DateTime(2026, 1, 10),
      status: BookingStatus.confirmed,
      qrData: 'EVT-B5-DC2026-RSV-E1E2',
    ),
    BookingModel(
      id: 'b6',
      userId: 'u6',
      userName: 'Carlos Rodriguez',
      userEmail: 'carlos@example.com',
      eventId: 'e6',
      eventTitle: 'Coachella Music Festival 2026',
      eventImageUrl: 'assets/images/event_coachella.jpg',
      venue: 'Empire Polo Club',
      eventDate: DateTime(2026, 4, 10),
      tierName: 'GA Pass',
      seats: ['GA'],
      subtotal: 449.00,
      serviceFee: 44.90,
      discount: 0,
      total: 493.90,
      paymentMethod: 'Credit Card',
      bookingDate: DateTime(2025, 10, 1),
      status: BookingStatus.confirmed,
      qrData: 'EVT-B6-COACH2026-GA',
    ),
    BookingModel(
      id: 'b7',
      userId: 'u7',
      userName: 'Aisha Patel',
      userEmail: 'aisha@example.com',
      eventId: 'e9',
      eventTitle: 'Ed Sheeran - Mathematics Tour',
      eventImageUrl: 'assets/images/event_ed_sheeran.jpg',
      venue: 'The O2 Arena',
      eventDate: DateTime(2026, 5, 15),
      tierName: 'General',
      seats: ['F3', 'F4', 'F5'],
      subtotal: 210.00,
      serviceFee: 21.00,
      discount: 0,
      total: 231.00,
      paymentMethod: 'UPI',
      bookingDate: DateTime(2026, 2, 1),
      status: BookingStatus.confirmed,
      qrData: 'EVT-B7-ES2026-GEN-F3F4F5',
    ),
    BookingModel(
      id: 'b8',
      userId: 'u8',
      userName: 'James Wilson',
      userEmail: 'james@example.com',
      eventId: 'e7',
      eventTitle: 'Disney on Ice - Frozen',
      eventImageUrl: 'assets/images/event_disney_on_ice.jpg',
      venue: 'Madison Square Garden',
      eventDate: DateTime(2026, 5, 1),
      tierName: 'Standard',
      seats: ['G1', 'G2', 'G3', 'G4'],
      subtotal: 180.00,
      serviceFee: 18.00,
      discount: 0,
      total: 198.00,
      paymentMethod: 'Credit Card',
      bookingDate: DateTime(2026, 1, 20),
      status: BookingStatus.confirmed,
      qrData: 'EVT-B8-DOI2026-STD-G1G2G3G4',
    ),
    BookingModel(
      id: 'b9',
      userId: 'u9',
      userName: 'Luna Kim',
      userEmail: 'luna@example.com',
      eventId: 'e8',
      eventTitle: 'UFC 300 - Championship Night',
      eventImageUrl: 'assets/images/event_ufc.jpg',
      venue: 'Staples Center',
      eventDate: DateTime(2026, 4, 20),
      tierName: 'Gold',
      seats: ['B5', 'B6'],
      subtotal: 1000.00,
      serviceFee: 100.00,
      discount: 0,
      total: 1100.00,
      paymentMethod: 'Credit Card',
      bookingDate: DateTime(2026, 1, 25),
      status: BookingStatus.confirmed,
      qrData: 'EVT-B9-UFC300-GOLD-B5B6',
    ),
    BookingModel(
      id: 'b10',
      userId: 'u3',
      userName: 'Sarah Connor',
      userEmail: 'sarah@example.com',
      eventId: 'e10',
      eventTitle: 'Trevor Noah - Off the Record',
      eventImageUrl: 'assets/images/event_trevor_noah.jpg',
      venue: 'Sydney Opera House',
      eventDate: DateTime(2026, 3, 30),
      tierName: 'Premium',
      seats: ['A2'],
      subtotal: 120.00,
      serviceFee: 12.00,
      discount: 0,
      total: 132.00,
      paymentMethod: 'Wallet',
      bookingDate: DateTime(2026, 2, 5),
      status: BookingStatus.confirmed,
      qrData: 'EVT-B10-TN2026-PREM-A2',
    ),
    BookingModel(
      id: 'b11',
      userId: 'u5',
      userName: 'Emily Davis',
      userEmail: 'emily@example.com',
      eventId: 'e1',
      eventTitle: 'Taylor Swift - Eras Tour',
      eventImageUrl: 'assets/images/event_taylor_swift.jpg',
      venue: 'Madison Square Garden',
      eventDate: DateTime(2026, 3, 15),
      tierName: 'General',
      seats: ['H7', 'H8'],
      subtotal: 179.98,
      serviceFee: 18.00,
      discount: 0,
      total: 197.98,
      paymentMethod: 'Net Banking',
      bookingDate: DateTime(2025, 11, 10),
      status: BookingStatus.cancelled,
      qrData: 'EVT-B11-TS2026-GEN-H7H8',
    ),
    BookingModel(
      id: 'b12',
      userId: 'u10',
      userName: 'David Brown',
      userEmail: 'david@example.com',
      eventId: 'e12',
      eventTitle: 'The Lion King - Broadway',
      eventImageUrl: 'assets/images/event_lion_king.jpg',
      venue: 'Minskoff Theatre',
      eventDate: DateTime(2026, 4, 15),
      tierName: 'Orchestra',
      seats: ['D5', 'D6'],
      subtotal: 358.00,
      serviceFee: 35.80,
      discount: 0,
      total: 393.80,
      paymentMethod: 'Credit Card',
      bookingDate: DateTime(2026, 2, 10),
      status: BookingStatus.confirmed,
      qrData: 'EVT-B12-LK2026-ORC-D5D6',
    ),
    BookingModel(
      id: 'b13',
      userId: 'u2',
      userName: 'John Doe',
      userEmail: 'john@example.com',
      eventId: 'e11',
      eventTitle: 'Wimbledon Finals 2026',
      eventImageUrl: 'assets/images/event_wimbledon.jpg',
      venue: 'All England Club',
      eventDate: DateTime(2026, 7, 12),
      tierName: 'Court Seat',
      seats: ['C10'],
      subtotal: 380.00,
      serviceFee: 38.00,
      discount: 0,
      total: 418.00,
      paymentMethod: 'Credit Card',
      bookingDate: DateTime(2026, 2, 15),
      status: BookingStatus.confirmed,
      qrData: 'EVT-B13-WIM2026-CS-C10',
    ),
    BookingModel(
      id: 'b14',
      userId: 'u4',
      userName: 'Mike Johnson',
      userEmail: 'mike@example.com',
      eventId: 'e13',
      eventTitle: 'Electric Daisy Carnival',
      eventImageUrl: 'assets/images/event_edc.jpg',
      venue: 'Las Vegas Motor Speedway',
      eventDate: DateTime(2026, 5, 22),
      tierName: '3-Day GA',
      seats: ['GA'],
      subtotal: 369.00,
      serviceFee: 36.90,
      discount: 0,
      total: 405.90,
      paymentMethod: 'Wallet',
      bookingDate: DateTime(2026, 1, 30),
      status: BookingStatus.cancelled,
      qrData: 'EVT-B14-EDC2026-GA',
    ),
    BookingModel(
      id: 'b15',
      userId: 'u7',
      userName: 'Aisha Patel',
      userEmail: 'aisha@example.com',
      eventId: 'e2',
      eventTitle: 'Coldplay - Music of the Spheres',
      eventImageUrl: 'assets/images/event_coldplay.jpg',
      venue: 'Wembley Stadium',
      eventDate: DateTime(2026, 3, 22),
      tierName: 'VIP',
      seats: ['A1', 'A2'],
      subtotal: 399.98,
      serviceFee: 40.00,
      discount: 0,
      total: 439.98,
      paymentMethod: 'Credit Card',
      bookingDate: DateTime(2025, 12, 25),
      status: BookingStatus.confirmed,
      qrData: 'EVT-B15-CP2026-VIP-A1A2',
    ),
    BookingModel(
      id: 'b16',
      userId: 'u6',
      userName: 'Carlos Rodriguez',
      userEmail: 'carlos@example.com',
      eventId: 'e5',
      eventTitle: 'Dave Chappelle - Live',
      eventImageUrl: 'assets/images/event_dave_chappelle.jpg',
      venue: 'Red Rocks Amphitheatre',
      eventDate: DateTime(2026, 3, 28),
      tierName: 'General Admission',
      seats: ['GA'],
      subtotal: 95.00,
      serviceFee: 9.50,
      discount: 0,
      total: 104.50,
      paymentMethod: 'UPI',
      bookingDate: DateTime(2026, 2, 18),
      status: BookingStatus.confirmed,
      qrData: 'EVT-B16-DC2026-GA',
    ),
    BookingModel(
      id: 'b17',
      userId: 'u9',
      userName: 'Luna Kim',
      userEmail: 'luna@example.com',
      eventId: 'e4',
      eventTitle: 'Hamilton - Musical',
      eventImageUrl: 'assets/images/event_hamilton.jpg',
      venue: 'Sydney Opera House',
      eventDate: DateTime(2026, 4, 5),
      tierName: 'Premium',
      seats: ['A8', 'A9'],
      subtotal: 550.00,
      serviceFee: 55.00,
      discount: 55.00,
      total: 550.00,
      promoCode: 'SAVE10',
      paymentMethod: 'Credit Card',
      bookingDate: DateTime(2026, 1, 15),
      status: BookingStatus.confirmed,
      qrData: 'EVT-B17-HAM2026-PREM-A8A9',
    ),
    BookingModel(
      id: 'b18',
      userId: 'u10',
      userName: 'David Brown',
      userEmail: 'david@example.com',
      eventId: 'e9',
      eventTitle: 'Ed Sheeran - Mathematics Tour',
      eventImageUrl: 'assets/images/event_ed_sheeran.jpg',
      venue: 'The O2 Arena',
      eventDate: DateTime(2026, 5, 15),
      tierName: 'VIP',
      seats: ['B3'],
      subtotal: 180.00,
      serviceFee: 18.00,
      discount: 0,
      total: 198.00,
      paymentMethod: 'Net Banking',
      bookingDate: DateTime(2026, 2, 20),
      status: BookingStatus.confirmed,
      qrData: 'EVT-B18-ES2026-VIP-B3',
    ),
    BookingModel(
      id: 'b19',
      userId: 'u8',
      userName: 'James Wilson',
      userEmail: 'james@example.com',
      eventId: 'e3',
      eventTitle: 'NBA Finals - Game 7',
      eventImageUrl: 'assets/images/event_nba_finals.jpg',
      venue: 'Staples Center',
      eventDate: DateTime(2026, 6, 18),
      tierName: 'Upper Level',
      seats: ['E9', 'E10'],
      subtotal: 300.00,
      serviceFee: 30.00,
      discount: 0,
      total: 330.00,
      paymentMethod: 'Wallet',
      bookingDate: DateTime(2026, 2, 12),
      status: BookingStatus.confirmed,
      qrData: 'EVT-B19-NBA2026-UL-E9E10',
    ),
    BookingModel(
      id: 'b20',
      userId: 'u5',
      userName: 'Emily Davis',
      userEmail: 'emily@example.com',
      eventId: 'e6',
      eventTitle: 'Coachella Music Festival 2026',
      eventImageUrl: 'assets/images/event_coachella.jpg',
      venue: 'Empire Polo Club',
      eventDate: DateTime(2026, 4, 10),
      tierName: 'VIP Pass',
      seats: ['VIP'],
      subtotal: 999.00,
      serviceFee: 99.90,
      discount: 99.90,
      total: 999.00,
      promoCode: 'SAVE10',
      paymentMethod: 'Credit Card',
      bookingDate: DateTime(2025, 9, 20),
      status: BookingStatus.confirmed,
      qrData: 'EVT-B20-COACH2026-VIP',
    ),
  ];

  // â”€â”€â”€ CATEGORIES â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  static const List<String> categories = [
    'All',
    'Concerts',
    'Sports',
    'Theatre',
    'Comedy',
    'Festivals',
    'Family',
  ];

  // â”€â”€â”€ TOP ARTISTS â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  static const List<Map<String, String>> topArtists = [
    {'name': 'Taylor Swift', 'image': 'assets/images/artist_taylor_swift.jpg'},
    {'name': 'Coldplay', 'image': 'assets/images/artist_coldplay.jpg'},
    {'name': 'Ed Sheeran', 'image': 'assets/images/artist_ed_sheeran.jpg'},
    {'name': 'Bad Bunny', 'image': 'assets/images/event_taylor_swift.jpg'},
    {'name': 'Billie Eilish', 'image': 'assets/images/artist_billie_eilish.jpg'},
    {'name': 'Dave Chappelle', 'image': 'assets/images/event_trevor_noah.jpg'},
  ];

  // â”€â”€â”€ ONBOARDING DATA â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  static const List<Map<String, String>> onboardingPages = [
    {
      'title': 'Discover Events Near You',
      'description': 'Find concerts, sports, theatre, comedy and more happening in your city.',
      'image': 'assets/images/venue_o2_arena.jpg',
    },
    {
      'title': 'Choose Your Perfect Seat',
      'description': 'Interactive seat maps let you pick the best view for an unforgettable experience.',
      'image': 'assets/images/venue_madison_sg.jpg',
    },
    {
      'title': 'Book in Seconds',
      'description': 'Fast, secure checkout with multiple payment options. Your tickets, your way.',
      'image': 'assets/images/venue_red_rocks.jpg',
    },
  ];

  // â”€â”€â”€ CITIES â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  static const List<String> cities = [
    'All Cities',
    'New York',
    'London',
    'Los Angeles',
    'Sydney',
    'Denver',
    'Las Vegas',
    'Indio',
  ];

  // â”€â”€â”€ TAKEN SEATS (pre-occupied for seat selection) â”€â”€â”€â”€â”€
  static const List<String> takenSeats = [
    'A1', 'A2', 'A7', 'A8',
    'B3', 'B4', 'B9',
    'C1', 'C5', 'C6', 'C10',
    'D2', 'D7', 'D8', 'D9',
    'E3', 'E4', 'E5',
    'F1', 'F6', 'F10',
    'G2', 'G8', 'G9',
    'H1', 'H5', 'H6', 'H10',
  ];

  static const List<String> vipSeats = [
    'A3', 'A4', 'A5', 'A6',
    'B1', 'B2', 'B5', 'B6', 'B7', 'B8',
  ];
}
