import '../../models/event_model.dart';
import '../../models/venue_model.dart';
import '../../models/user_model.dart';
import '../../models/booking_model.dart';
import '../../models/ticket_model.dart';

class MockData {
  // ─── VENUES ────────────────────────────────────────────
  static final List<VenueModel> venues = [
    VenueModel(
      id: 'v1',
      name: 'Madison Square Garden',
      city: 'New York',
      address: '4 Pennsylvania Plaza, New York, NY 10001',
      capacity: 20000,
      imageUrl: 'https://images.unsplash.com/photo-1540039155733-5bb30b53aa14?w=800',
      rows: 10,
      seatsPerRow: 12,
    ),
    VenueModel(
      id: 'v2',
      name: 'The O2 Arena',
      city: 'London',
      address: 'Peninsula Square, London SE10 0DX',
      capacity: 20000,
      imageUrl: 'https://images.unsplash.com/photo-1459749411175-04bf5292ceea?w=800',
      rows: 10,
      seatsPerRow: 12,
    ),
    VenueModel(
      id: 'v3',
      name: 'Staples Center',
      city: 'Los Angeles',
      address: '1111 S Figueroa St, Los Angeles, CA 90015',
      capacity: 21000,
      imageUrl: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=800',
      rows: 8,
      seatsPerRow: 10,
    ),
    VenueModel(
      id: 'v4',
      name: 'Wembley Stadium',
      city: 'London',
      address: 'London HA9 0WS, United Kingdom',
      capacity: 90000,
      imageUrl: 'https://images.unsplash.com/photo-1522158637959-30385a09e0da?w=800',
      rows: 12,
      seatsPerRow: 14,
    ),
    VenueModel(
      id: 'v5',
      name: 'Sydney Opera House',
      city: 'Sydney',
      address: 'Bennelong Point, Sydney NSW 2000',
      capacity: 5738,
      imageUrl: 'https://images.unsplash.com/photo-1523059623039-a9ed027e7fad?w=800',
      rows: 8,
      seatsPerRow: 10,
    ),
    VenueModel(
      id: 'v6',
      name: 'Red Rocks Amphitheatre',
      city: 'Denver',
      address: '18300 W Alameda Pkwy, Morrison, CO 80465',
      capacity: 9525,
      imageUrl: 'https://images.unsplash.com/photo-1501281668745-f7f57925c3b4?w=800',
      rows: 10,
      seatsPerRow: 12,
    ),
  ];

  // ─── EVENTS ────────────────────────────────────────────
  static final List<EventModel> events = [
    EventModel(
      id: 'e1',
      title: 'Taylor Swift - Eras Tour',
      imageUrl: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=800',
      category: 'Concerts',
      date: DateTime(2026, 3, 15),
      time: '7:00 PM',
      venueId: 'v1',
      venueName: 'Madison Square Garden',
      city: 'New York',
      artists: ['Taylor Swift'],
      description:
          'Experience the magic of Taylor Swift\'s record-breaking Eras Tour! A spectacular journey through her musical history featuring songs from every album. An unforgettable night of music, visuals, and pure artistry.',
      ticketTiers: [
        TicketTier(name: 'General', price: 89.99, totalQuantity: 5000, soldQuantity: 4200),
        TicketTier(name: 'VIP', price: 249.99, totalQuantity: 1000, soldQuantity: 850),
        TicketTier(name: 'Platinum', price: 499.99, totalQuantity: 200, soldQuantity: 150),
      ],
      isFeatured: true,
      isTrending: true,
      rating: 4.9,
      reviewCount: 2450,
    ),
    EventModel(
      id: 'e2',
      title: 'Coldplay - Music of the Spheres',
      imageUrl: 'https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?w=800',
      category: 'Concerts',
      date: DateTime(2026, 3, 22),
      time: '8:00 PM',
      venueId: 'v4',
      venueName: 'Wembley Stadium',
      city: 'London',
      artists: ['Coldplay'],
      description:
          'Coldplay brings their spectacular Music of the Spheres World Tour to Wembley Stadium. Featuring their greatest hits alongside new material, with stunning visual effects and LED wristbands for every attendee.',
      ticketTiers: [
        TicketTier(name: 'General', price: 75.00, totalQuantity: 30000, soldQuantity: 28000),
        TicketTier(name: 'VIP', price: 199.99, totalQuantity: 5000, soldQuantity: 4600),
        TicketTier(name: 'Platinum', price: 399.99, totalQuantity: 500, soldQuantity: 400),
      ],
      isFeatured: true,
      isTrending: true,
      rating: 4.8,
      reviewCount: 1890,
    ),
    EventModel(
      id: 'e3',
      title: 'NBA Finals - Game 7',
      imageUrl: 'https://images.unsplash.com/photo-1546519638-68e109498ffc?w=800',
      category: 'Sports',
      date: DateTime(2026, 6, 18),
      time: '9:00 PM',
      venueId: 'v3',
      venueName: 'Staples Center',
      city: 'Los Angeles',
      artists: ['Lakers vs Celtics'],
      description:
          'The ultimate showdown! Watch the NBA Finals Game 7 live at the Staples Center. Two legendary teams battle it out for the championship in what promises to be an electrifying night of basketball.',
      ticketTiers: [
        TicketTier(name: 'Upper Level', price: 150.00, totalQuantity: 8000, soldQuantity: 7800),
        TicketTier(name: 'Lower Level', price: 350.00, totalQuantity: 3000, soldQuantity: 2900),
        TicketTier(name: 'Courtside', price: 1200.00, totalQuantity: 100, soldQuantity: 95),
      ],
      isFeatured: true,
      isTrending: true,
      rating: 4.7,
      reviewCount: 890,
      status: 'Active',
    ),
    EventModel(
      id: 'e4',
      title: 'Hamilton - Musical',
      imageUrl: 'https://images.unsplash.com/photo-1507676184212-d03ab07a01bf?w=800',
      category: 'Theatre',
      date: DateTime(2026, 4, 5),
      time: '2:00 PM',
      venueId: 'v5',
      venueName: 'Sydney Opera House',
      city: 'Sydney',
      artists: ['Lin-Manuel Miranda Production'],
      description:
          'The revolutionary musical that took the world by storm. Hamilton tells the story of America\'s founding father Alexander Hamilton through hip-hop, R&B, and traditional show tunes.',
      ticketTiers: [
        TicketTier(name: 'Balcony', price: 65.00, totalQuantity: 2000, soldQuantity: 1800),
        TicketTier(name: 'Orchestra', price: 145.00, totalQuantity: 1000, soldQuantity: 920),
        TicketTier(name: 'Premium', price: 275.00, totalQuantity: 300, soldQuantity: 280),
      ],
      isFeatured: false,
      isTrending: true,
      rating: 4.9,
      reviewCount: 3200,
    ),
    EventModel(
      id: 'e5',
      title: 'Dave Chappelle - Live',
      imageUrl: 'https://images.unsplash.com/photo-1585699324551-f6c309eedeca?w=800',
      category: 'Comedy',
      date: DateTime(2026, 3, 28),
      time: '9:30 PM',
      venueId: 'v6',
      venueName: 'Red Rocks Amphitheatre',
      city: 'Denver',
      artists: ['Dave Chappelle'],
      description:
          'The legendary Dave Chappelle brings his iconic stand-up comedy to the breathtaking Red Rocks Amphitheatre. An intimate evening of sharp wit, storytelling, and unforgettable laughs under the stars.',
      ticketTiers: [
        TicketTier(name: 'General Admission', price: 95.00, totalQuantity: 5000, soldQuantity: 4500),
        TicketTier(name: 'Reserved', price: 175.00, totalQuantity: 1500, soldQuantity: 1300),
      ],
      isFeatured: false,
      isTrending: false,
      rating: 4.6,
      reviewCount: 670,
    ),
    EventModel(
      id: 'e6',
      title: 'Coachella Music Festival 2026',
      imageUrl: 'https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=800',
      category: 'Festivals',
      date: DateTime(2026, 4, 10),
      time: '12:00 PM',
      venueId: 'v6',
      venueName: 'Empire Polo Club',
      city: 'Indio',
      artists: ['Bad Bunny', 'Billie Eilish', 'Frank Ocean', 'BLACKPINK'],
      description:
          'The world\'s most iconic music festival returns! Three days of incredible performances across multiple stages, immersive art installations, and unforgettable experiences in the California desert.',
      ticketTiers: [
        TicketTier(name: 'GA Pass', price: 449.00, totalQuantity: 50000, soldQuantity: 48000),
        TicketTier(name: 'VIP Pass', price: 999.00, totalQuantity: 5000, soldQuantity: 4800),
        TicketTier(name: 'Safari Camping', price: 2500.00, totalQuantity: 200, soldQuantity: 200),
      ],
      isFeatured: true,
      isTrending: true,
      rating: 4.8,
      reviewCount: 5600,
    ),
    EventModel(
      id: 'e7',
      title: 'Disney on Ice - Frozen',
      imageUrl: 'https://images.unsplash.com/photo-1513106580091-1d82408b8cd6?w=800',
      category: 'Family',
      date: DateTime(2026, 5, 1),
      time: '3:00 PM',
      venueId: 'v1',
      venueName: 'Madison Square Garden',
      city: 'New York',
      artists: ['Disney Performers'],
      description:
          'Let it go! Join Anna, Elsa, Olaf, and the gang in this magical ice skating spectacular. A family-friendly show that brings the beloved Frozen story to life on ice with stunning costumes and choreography.',
      ticketTiers: [
        TicketTier(name: 'Standard', price: 45.00, totalQuantity: 10000, soldQuantity: 7500),
        TicketTier(name: 'Premium', price: 85.00, totalQuantity: 3000, soldQuantity: 2200),
        TicketTier(name: 'Front Row', price: 145.00, totalQuantity: 500, soldQuantity: 350),
      ],
      isFeatured: false,
      isTrending: false,
      rating: 4.5,
      reviewCount: 1200,
    ),
    EventModel(
      id: 'e8',
      title: 'UFC 300 - Championship Night',
      imageUrl: 'https://images.unsplash.com/photo-1549719386-74dfcbf7dbed?w=800',
      category: 'Sports',
      date: DateTime(2026, 4, 20),
      time: '10:00 PM',
      venueId: 'v3',
      venueName: 'Staples Center',
      city: 'Los Angeles',
      artists: ['Main Event TBA'],
      description:
          'UFC 300 promises to be the biggest MMA event in history! Multiple championship bouts headline this historic milestone card featuring the best fighters on the planet.',
      ticketTiers: [
        TicketTier(name: 'General', price: 200.00, totalQuantity: 8000, soldQuantity: 7600),
        TicketTier(name: 'Gold', price: 500.00, totalQuantity: 2000, soldQuantity: 1900),
        TicketTier(name: 'Cageside', price: 1500.00, totalQuantity: 100, soldQuantity: 90),
      ],
      isFeatured: false,
      isTrending: true,
      rating: 4.7,
      reviewCount: 980,
    ),
    EventModel(
      id: 'e9',
      title: 'Ed Sheeran - Mathematics Tour',
      imageUrl: 'https://images.unsplash.com/photo-1501386761578-eac5c94b800a?w=800',
      category: 'Concerts',
      date: DateTime(2026, 5, 15),
      time: '7:30 PM',
      venueId: 'v2',
      venueName: 'The O2 Arena',
      city: 'London',
      artists: ['Ed Sheeran'],
      description:
          'Ed Sheeran\'s Mathematics Tour comes to The O2 Arena. Experience the singer-songwriter\'s incredible one-man show with his loop pedal magic, performing chart-topping hits in an intimate yet grand setting.',
      ticketTiers: [
        TicketTier(name: 'General', price: 70.00, totalQuantity: 8000, soldQuantity: 7200),
        TicketTier(name: 'VIP', price: 180.00, totalQuantity: 2000, soldQuantity: 1800),
        TicketTier(name: 'Platinum', price: 350.00, totalQuantity: 300, soldQuantity: 250),
      ],
      isFeatured: false,
      isTrending: false,
      rating: 4.8,
      reviewCount: 2100,
    ),
    EventModel(
      id: 'e10',
      title: 'Trevor Noah - Off the Record',
      imageUrl: 'https://images.unsplash.com/photo-1527224857830-43a7acc85260?w=800',
      category: 'Comedy',
      date: DateTime(2026, 3, 30),
      time: '8:00 PM',
      venueId: 'v5',
      venueName: 'Sydney Opera House',
      city: 'Sydney',
      artists: ['Trevor Noah'],
      description:
          'Former Daily Show host Trevor Noah brings his sharp, globally-inspired comedy to Sydney. A masterful blend of cultural commentary, personal anecdotes, and razor-sharp observations.',
      ticketTiers: [
        TicketTier(name: 'Standard', price: 55.00, totalQuantity: 3000, soldQuantity: 2700),
        TicketTier(name: 'Premium', price: 120.00, totalQuantity: 800, soldQuantity: 720),
      ],
      isFeatured: false,
      isTrending: false,
      rating: 4.6,
      reviewCount: 540,
    ),
    EventModel(
      id: 'e11',
      title: 'Wimbledon Finals 2026',
      imageUrl: 'https://images.unsplash.com/photo-1622279457486-62dcc4a431d6?w=800',
      category: 'Sports',
      date: DateTime(2026, 7, 12),
      time: '2:00 PM',
      venueId: 'v2',
      venueName: 'All England Club',
      city: 'London',
      artists: ['TBA Finalists'],
      description:
          'The most prestigious tennis tournament in the world. Watch the Men\'s Singles Final at the legendary Centre Court with its retractable roof and perfectly manicured grass courts.',
      ticketTiers: [
        TicketTier(name: 'Grounds Pass', price: 120.00, totalQuantity: 15000, soldQuantity: 14500),
        TicketTier(name: 'Court Seat', price: 380.00, totalQuantity: 5000, soldQuantity: 4900),
        TicketTier(name: 'Debenture', price: 850.00, totalQuantity: 500, soldQuantity: 480),
      ],
      isFeatured: false,
      isTrending: true,
      rating: 4.9,
      reviewCount: 1550,
    ),
    EventModel(
      id: 'e12',
      title: 'The Lion King - Broadway',
      imageUrl: 'https://images.unsplash.com/photo-1503095396549-807759245b35?w=800',
      category: 'Theatre',
      date: DateTime(2026, 4, 15),
      time: '7:30 PM',
      venueId: 'v1',
      venueName: 'Minskoff Theatre',
      city: 'New York',
      artists: ['Broadway Cast'],
      description:
          'The award-winning musical adapted from the Disney animated classic. Stunning puppetry, breathtaking costumes, and unforgettable music by Elton John and Tim Rice make this a must-see theatrical experience.',
      ticketTiers: [
        TicketTier(name: 'Rear Mezzanine', price: 79.00, totalQuantity: 800, soldQuantity: 600),
        TicketTier(name: 'Orchestra', price: 179.00, totalQuantity: 500, soldQuantity: 430),
        TicketTier(name: 'Premium Orchestra', price: 299.00, totalQuantity: 150, soldQuantity: 120),
      ],
      isFeatured: false,
      isTrending: false,
      rating: 4.8,
      reviewCount: 4200,
    ),
    EventModel(
      id: 'e13',
      title: 'Electric Daisy Carnival',
      imageUrl: 'https://images.unsplash.com/photo-1429962714451-bb934ecdc4ec?w=800',
      category: 'Festivals',
      date: DateTime(2026, 5, 22),
      time: '5:00 PM',
      venueId: 'v3',
      venueName: 'Las Vegas Motor Speedway',
      city: 'Las Vegas',
      artists: ['Tiësto', 'Martin Garrix', 'Zedd', 'Marshmello'],
      description:
          'The world\'s largest dance music festival transforms the Las Vegas Motor Speedway into a neon wonderland. Three nights of electronic music across 8 stages with carnival rides and art installations.',
      ticketTiers: [
        TicketTier(name: '3-Day GA', price: 369.00, totalQuantity: 80000, soldQuantity: 75000),
        TicketTier(name: '3-Day VIP', price: 799.00, totalQuantity: 10000, soldQuantity: 9200),
        TicketTier(name: 'Bottle Service', price: 3000.00, totalQuantity: 100, soldQuantity: 85),
      ],
      isFeatured: true,
      isTrending: false,
      rating: 4.7,
      reviewCount: 3400,
    ),
  ];

  // ─── USERS ─────────────────────────────────────────────
  static final List<UserModel> users = [
    UserModel(
      id: 'u1',
      fullName: 'Admin User',
      email: 'admin@app.com',
      phone: '+1 555-0100',
      avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200',
      isAdmin: true,
      joinDate: DateTime(2024, 1, 1),
      bookingCount: 5,
    ),
    UserModel(
      id: 'u2',
      fullName: 'John Doe',
      email: 'john@example.com',
      phone: '+1 555-0101',
      avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200',
      joinDate: DateTime(2024, 6, 15),
      bookingCount: 12,
    ),
    UserModel(
      id: 'u3',
      fullName: 'Sarah Connor',
      email: 'sarah@example.com',
      phone: '+1 555-0102',
      avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200',
      joinDate: DateTime(2024, 8, 22),
      bookingCount: 8,
    ),
    UserModel(
      id: 'u4',
      fullName: 'Mike Johnson',
      email: 'mike@example.com',
      phone: '+1 555-0103',
      avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200',
      joinDate: DateTime(2025, 1, 10),
      bookingCount: 3,
    ),
    UserModel(
      id: 'u5',
      fullName: 'Emily Davis',
      email: 'emily@example.com',
      phone: '+1 555-0104',
      avatarUrl: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200',
      joinDate: DateTime(2025, 2, 28),
      bookingCount: 15,
    ),
    UserModel(
      id: 'u6',
      fullName: 'Carlos Rodriguez',
      email: 'carlos@example.com',
      phone: '+1 555-0105',
      avatarUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=200',
      joinDate: DateTime(2025, 3, 5),
      bookingCount: 6,
    ),
    UserModel(
      id: 'u7',
      fullName: 'Aisha Patel',
      email: 'aisha@example.com',
      phone: '+44 7700-900123',
      avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200',
      joinDate: DateTime(2025, 4, 12),
      bookingCount: 9,
    ),
    UserModel(
      id: 'u8',
      fullName: 'James Wilson',
      email: 'james@example.com',
      phone: '+1 555-0106',
      avatarUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=200',
      joinDate: DateTime(2025, 5, 20),
      bookingCount: 2,
    ),
    UserModel(
      id: 'u9',
      fullName: 'Luna Kim',
      email: 'luna@example.com',
      phone: '+82 10-1234-5678',
      avatarUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=200',
      joinDate: DateTime(2025, 7, 1),
      bookingCount: 11,
    ),
    UserModel(
      id: 'u10',
      fullName: 'David Brown',
      email: 'david@example.com',
      phone: '+1 555-0107',
      avatarUrl: 'https://images.unsplash.com/photo-1463453091185-61582044d556?w=200',
      joinDate: DateTime(2025, 8, 15),
      bookingCount: 4,
    ),
  ];

  // ─── BOOKINGS ──────────────────────────────────────────
  static final List<BookingModel> bookings = [
    BookingModel(
      id: 'b1',
      userId: 'u2',
      userName: 'John Doe',
      userEmail: 'john@example.com',
      eventId: 'e1',
      eventTitle: 'Taylor Swift - Eras Tour',
      eventImageUrl: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=800',
      venue: 'Madison Square Garden',
      eventDate: DateTime(2026, 3, 15),
      tierName: 'VIP',
      seats: ['A5', 'A6'],
      subtotal: 499.98,
      serviceFee: 50.00,
      discount: 0,
      total: 549.98,
      paymentMethod: 'Credit Card',
      bookingDate: DateTime(2025, 12, 1),
      status: BookingStatus.confirmed,
      qrData: 'EVT-B1-TS2026-VIP-A5A6',
    ),
    BookingModel(
      id: 'b2',
      userId: 'u3',
      userName: 'Sarah Connor',
      userEmail: 'sarah@example.com',
      eventId: 'e2',
      eventTitle: 'Coldplay - Music of the Spheres',
      eventImageUrl: 'https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?w=800',
      venue: 'Wembley Stadium',
      eventDate: DateTime(2026, 3, 22),
      tierName: 'General',
      seats: ['D2', 'D3', 'D4'],
      subtotal: 225.00,
      serviceFee: 22.50,
      discount: 22.50,
      total: 225.00,
      promoCode: 'SAVE10',
      paymentMethod: 'UPI',
      bookingDate: DateTime(2025, 11, 15),
      status: BookingStatus.confirmed,
      qrData: 'EVT-B2-CP2026-GEN-D2D3D4',
    ),
    BookingModel(
      id: 'b3',
      userId: 'u4',
      userName: 'Mike Johnson',
      userEmail: 'mike@example.com',
      eventId: 'e3',
      eventTitle: 'NBA Finals - Game 7',
      eventImageUrl: 'https://images.unsplash.com/photo-1546519638-68e109498ffc?w=800',
      venue: 'Staples Center',
      eventDate: DateTime(2026, 6, 18),
      tierName: 'Lower Level',
      seats: ['B8'],
      subtotal: 350.00,
      serviceFee: 35.00,
      discount: 0,
      total: 385.00,
      paymentMethod: 'Net Banking',
      bookingDate: DateTime(2026, 1, 5),
      status: BookingStatus.confirmed,
      qrData: 'EVT-B3-NBA2026-LL-B8',
    ),
    BookingModel(
      id: 'b4',
      userId: 'u5',
      userName: 'Emily Davis',
      userEmail: 'emily@example.com',
      eventId: 'e4',
      eventTitle: 'Hamilton - Musical',
      eventImageUrl: 'https://images.unsplash.com/photo-1507676184212-d03ab07a01bf?w=800',
      venue: 'Sydney Opera House',
      eventDate: DateTime(2026, 4, 5),
      tierName: 'Orchestra',
      seats: ['C3', 'C4'],
      subtotal: 290.00,
      serviceFee: 29.00,
      discount: 0,
      total: 319.00,
      paymentMethod: 'Credit Card',
      bookingDate: DateTime(2025, 12, 20),
      status: BookingStatus.confirmed,
      qrData: 'EVT-B4-HAM2026-ORC-C3C4',
    ),
    BookingModel(
      id: 'b5',
      userId: 'u2',
      userName: 'John Doe',
      userEmail: 'john@example.com',
      eventId: 'e5',
      eventTitle: 'Dave Chappelle - Live',
      eventImageUrl: 'https://images.unsplash.com/photo-1585699324551-f6c309eedeca?w=800',
      venue: 'Red Rocks Amphitheatre',
      eventDate: DateTime(2026, 3, 28),
      tierName: 'Reserved',
      seats: ['E1', 'E2'],
      subtotal: 350.00,
      serviceFee: 35.00,
      discount: 35.00,
      total: 350.00,
      promoCode: 'SAVE10',
      paymentMethod: 'Wallet',
      bookingDate: DateTime(2026, 1, 10),
      status: BookingStatus.confirmed,
      qrData: 'EVT-B5-DC2026-RSV-E1E2',
    ),
    BookingModel(
      id: 'b6',
      userId: 'u6',
      userName: 'Carlos Rodriguez',
      userEmail: 'carlos@example.com',
      eventId: 'e6',
      eventTitle: 'Coachella Music Festival 2026',
      eventImageUrl: 'https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=800',
      venue: 'Empire Polo Club',
      eventDate: DateTime(2026, 4, 10),
      tierName: 'GA Pass',
      seats: ['GA'],
      subtotal: 449.00,
      serviceFee: 44.90,
      discount: 0,
      total: 493.90,
      paymentMethod: 'Credit Card',
      bookingDate: DateTime(2025, 10, 1),
      status: BookingStatus.confirmed,
      qrData: 'EVT-B6-COACH2026-GA',
    ),
    BookingModel(
      id: 'b7',
      userId: 'u7',
      userName: 'Aisha Patel',
      userEmail: 'aisha@example.com',
      eventId: 'e9',
      eventTitle: 'Ed Sheeran - Mathematics Tour',
      eventImageUrl: 'https://images.unsplash.com/photo-1501386761578-eac5c94b800a?w=800',
      venue: 'The O2 Arena',
      eventDate: DateTime(2026, 5, 15),
      tierName: 'General',
      seats: ['F3', 'F4', 'F5'],
      subtotal: 210.00,
      serviceFee: 21.00,
      discount: 0,
      total: 231.00,
      paymentMethod: 'UPI',
      bookingDate: DateTime(2026, 2, 1),
      status: BookingStatus.confirmed,
      qrData: 'EVT-B7-ES2026-GEN-F3F4F5',
    ),
    BookingModel(
      id: 'b8',
      userId: 'u8',
      userName: 'James Wilson',
      userEmail: 'james@example.com',
      eventId: 'e7',
      eventTitle: 'Disney on Ice - Frozen',
      eventImageUrl: 'https://images.unsplash.com/photo-1513106580091-1d82408b8cd6?w=800',
      venue: 'Madison Square Garden',
      eventDate: DateTime(2026, 5, 1),
      tierName: 'Standard',
      seats: ['G1', 'G2', 'G3', 'G4'],
      subtotal: 180.00,
      serviceFee: 18.00,
      discount: 0,
      total: 198.00,
      paymentMethod: 'Credit Card',
      bookingDate: DateTime(2026, 1, 20),
      status: BookingStatus.confirmed,
      qrData: 'EVT-B8-DOI2026-STD-G1G2G3G4',
    ),
    BookingModel(
      id: 'b9',
      userId: 'u9',
      userName: 'Luna Kim',
      userEmail: 'luna@example.com',
      eventId: 'e8',
      eventTitle: 'UFC 300 - Championship Night',
      eventImageUrl: 'https://images.unsplash.com/photo-1549719386-74dfcbf7dbed?w=800',
      venue: 'Staples Center',
      eventDate: DateTime(2026, 4, 20),
      tierName: 'Gold',
      seats: ['B5', 'B6'],
      subtotal: 1000.00,
      serviceFee: 100.00,
      discount: 0,
      total: 1100.00,
      paymentMethod: 'Credit Card',
      bookingDate: DateTime(2026, 1, 25),
      status: BookingStatus.confirmed,
      qrData: 'EVT-B9-UFC300-GOLD-B5B6',
    ),
    BookingModel(
      id: 'b10',
      userId: 'u3',
      userName: 'Sarah Connor',
      userEmail: 'sarah@example.com',
      eventId: 'e10',
      eventTitle: 'Trevor Noah - Off the Record',
      eventImageUrl: 'https://images.unsplash.com/photo-1527224857830-43a7acc85260?w=800',
      venue: 'Sydney Opera House',
      eventDate: DateTime(2026, 3, 30),
      tierName: 'Premium',
      seats: ['A2'],
      subtotal: 120.00,
      serviceFee: 12.00,
      discount: 0,
      total: 132.00,
      paymentMethod: 'Wallet',
      bookingDate: DateTime(2026, 2, 5),
      status: BookingStatus.confirmed,
      qrData: 'EVT-B10-TN2026-PREM-A2',
    ),
    BookingModel(
      id: 'b11',
      userId: 'u5',
      userName: 'Emily Davis',
      userEmail: 'emily@example.com',
      eventId: 'e1',
      eventTitle: 'Taylor Swift - Eras Tour',
      eventImageUrl: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=800',
      venue: 'Madison Square Garden',
      eventDate: DateTime(2026, 3, 15),
      tierName: 'General',
      seats: ['H7', 'H8'],
      subtotal: 179.98,
      serviceFee: 18.00,
      discount: 0,
      total: 197.98,
      paymentMethod: 'Net Banking',
      bookingDate: DateTime(2025, 11, 10),
      status: BookingStatus.cancelled,
      qrData: 'EVT-B11-TS2026-GEN-H7H8',
    ),
    BookingModel(
      id: 'b12',
      userId: 'u10',
      userName: 'David Brown',
      userEmail: 'david@example.com',
      eventId: 'e12',
      eventTitle: 'The Lion King - Broadway',
      eventImageUrl: 'https://images.unsplash.com/photo-1503095396549-807759245b35?w=800',
      venue: 'Minskoff Theatre',
      eventDate: DateTime(2026, 4, 15),
      tierName: 'Orchestra',
      seats: ['D5', 'D6'],
      subtotal: 358.00,
      serviceFee: 35.80,
      discount: 0,
      total: 393.80,
      paymentMethod: 'Credit Card',
      bookingDate: DateTime(2026, 2, 10),
      status: BookingStatus.confirmed,
      qrData: 'EVT-B12-LK2026-ORC-D5D6',
    ),
    BookingModel(
      id: 'b13',
      userId: 'u2',
      userName: 'John Doe',
      userEmail: 'john@example.com',
      eventId: 'e11',
      eventTitle: 'Wimbledon Finals 2026',
      eventImageUrl: 'https://images.unsplash.com/photo-1622279457486-62dcc4a431d6?w=800',
      venue: 'All England Club',
      eventDate: DateTime(2026, 7, 12),
      tierName: 'Court Seat',
      seats: ['C10'],
      subtotal: 380.00,
      serviceFee: 38.00,
      discount: 0,
      total: 418.00,
      paymentMethod: 'Credit Card',
      bookingDate: DateTime(2026, 2, 15),
      status: BookingStatus.confirmed,
      qrData: 'EVT-B13-WIM2026-CS-C10',
    ),
    BookingModel(
      id: 'b14',
      userId: 'u4',
      userName: 'Mike Johnson',
      userEmail: 'mike@example.com',
      eventId: 'e13',
      eventTitle: 'Electric Daisy Carnival',
      eventImageUrl: 'https://images.unsplash.com/photo-1429962714451-bb934ecdc4ec?w=800',
      venue: 'Las Vegas Motor Speedway',
      eventDate: DateTime(2026, 5, 22),
      tierName: '3-Day GA',
      seats: ['GA'],
      subtotal: 369.00,
      serviceFee: 36.90,
      discount: 0,
      total: 405.90,
      paymentMethod: 'Wallet',
      bookingDate: DateTime(2026, 1, 30),
      status: BookingStatus.cancelled,
      qrData: 'EVT-B14-EDC2026-GA',
    ),
    BookingModel(
      id: 'b15',
      userId: 'u7',
      userName: 'Aisha Patel',
      userEmail: 'aisha@example.com',
      eventId: 'e2',
      eventTitle: 'Coldplay - Music of the Spheres',
      eventImageUrl: 'https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?w=800',
      venue: 'Wembley Stadium',
      eventDate: DateTime(2026, 3, 22),
      tierName: 'VIP',
      seats: ['A1', 'A2'],
      subtotal: 399.98,
      serviceFee: 40.00,
      discount: 0,
      total: 439.98,
      paymentMethod: 'Credit Card',
      bookingDate: DateTime(2025, 12, 25),
      status: BookingStatus.confirmed,
      qrData: 'EVT-B15-CP2026-VIP-A1A2',
    ),
    BookingModel(
      id: 'b16',
      userId: 'u6',
      userName: 'Carlos Rodriguez',
      userEmail: 'carlos@example.com',
      eventId: 'e5',
      eventTitle: 'Dave Chappelle - Live',
      eventImageUrl: 'https://images.unsplash.com/photo-1585699324551-f6c309eedeca?w=800',
      venue: 'Red Rocks Amphitheatre',
      eventDate: DateTime(2026, 3, 28),
      tierName: 'General Admission',
      seats: ['GA'],
      subtotal: 95.00,
      serviceFee: 9.50,
      discount: 0,
      total: 104.50,
      paymentMethod: 'UPI',
      bookingDate: DateTime(2026, 2, 18),
      status: BookingStatus.confirmed,
      qrData: 'EVT-B16-DC2026-GA',
    ),
    BookingModel(
      id: 'b17',
      userId: 'u9',
      userName: 'Luna Kim',
      userEmail: 'luna@example.com',
      eventId: 'e4',
      eventTitle: 'Hamilton - Musical',
      eventImageUrl: 'https://images.unsplash.com/photo-1507676184212-d03ab07a01bf?w=800',
      venue: 'Sydney Opera House',
      eventDate: DateTime(2026, 4, 5),
      tierName: 'Premium',
      seats: ['A8', 'A9'],
      subtotal: 550.00,
      serviceFee: 55.00,
      discount: 55.00,
      total: 550.00,
      promoCode: 'SAVE10',
      paymentMethod: 'Credit Card',
      bookingDate: DateTime(2026, 1, 15),
      status: BookingStatus.confirmed,
      qrData: 'EVT-B17-HAM2026-PREM-A8A9',
    ),
    BookingModel(
      id: 'b18',
      userId: 'u10',
      userName: 'David Brown',
      userEmail: 'david@example.com',
      eventId: 'e9',
      eventTitle: 'Ed Sheeran - Mathematics Tour',
      eventImageUrl: 'https://images.unsplash.com/photo-1501386761578-eac5c94b800a?w=800',
      venue: 'The O2 Arena',
      eventDate: DateTime(2026, 5, 15),
      tierName: 'VIP',
      seats: ['B3'],
      subtotal: 180.00,
      serviceFee: 18.00,
      discount: 0,
      total: 198.00,
      paymentMethod: 'Net Banking',
      bookingDate: DateTime(2026, 2, 20),
      status: BookingStatus.confirmed,
      qrData: 'EVT-B18-ES2026-VIP-B3',
    ),
    BookingModel(
      id: 'b19',
      userId: 'u8',
      userName: 'James Wilson',
      userEmail: 'james@example.com',
      eventId: 'e3',
      eventTitle: 'NBA Finals - Game 7',
      eventImageUrl: 'https://images.unsplash.com/photo-1546519638-68e109498ffc?w=800',
      venue: 'Staples Center',
      eventDate: DateTime(2026, 6, 18),
      tierName: 'Upper Level',
      seats: ['E9', 'E10'],
      subtotal: 300.00,
      serviceFee: 30.00,
      discount: 0,
      total: 330.00,
      paymentMethod: 'Wallet',
      bookingDate: DateTime(2026, 2, 12),
      status: BookingStatus.confirmed,
      qrData: 'EVT-B19-NBA2026-UL-E9E10',
    ),
    BookingModel(
      id: 'b20',
      userId: 'u5',
      userName: 'Emily Davis',
      userEmail: 'emily@example.com',
      eventId: 'e6',
      eventTitle: 'Coachella Music Festival 2026',
      eventImageUrl: 'https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=800',
      venue: 'Empire Polo Club',
      eventDate: DateTime(2026, 4, 10),
      tierName: 'VIP Pass',
      seats: ['VIP'],
      subtotal: 999.00,
      serviceFee: 99.90,
      discount: 99.90,
      total: 999.00,
      promoCode: 'SAVE10',
      paymentMethod: 'Credit Card',
      bookingDate: DateTime(2025, 9, 20),
      status: BookingStatus.confirmed,
      qrData: 'EVT-B20-COACH2026-VIP',
    ),
  ];

  // ─── CATEGORIES ────────────────────────────────────────
  static const List<String> categories = [
    'All',
    'Concerts',
    'Sports',
    'Theatre',
    'Comedy',
    'Festivals',
    'Family',
  ];

  // ─── TOP ARTISTS ───────────────────────────────────────
  static const List<Map<String, String>> topArtists = [
    {'name': 'Taylor Swift', 'image': 'https://images.unsplash.com/photo-1516575150278-77136aed6920?w=200'},
    {'name': 'Coldplay', 'image': 'https://images.unsplash.com/photo-1498038432885-c6f3f1b912ee?w=200'},
    {'name': 'Ed Sheeran', 'image': 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=200'},
    {'name': 'Bad Bunny', 'image': 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=200'},
    {'name': 'Billie Eilish', 'image': 'https://images.unsplash.com/photo-1514320291840-2e0a9bf2a9ae?w=200'},
    {'name': 'Dave Chappelle', 'image': 'https://images.unsplash.com/photo-1527224857830-43a7acc85260?w=200'},
  ];

  // ─── ONBOARDING DATA ──────────────────────────────────
  static const List<Map<String, String>> onboardingPages = [
    {
      'title': 'Discover Events Near You',
      'description': 'Find concerts, sports, theatre, comedy and more happening in your city.',
      'image': 'https://images.unsplash.com/photo-1459749411175-04bf5292ceea?w=800',
    },
    {
      'title': 'Choose Your Perfect Seat',
      'description': 'Interactive seat maps let you pick the best view for an unforgettable experience.',
      'image': 'https://images.unsplash.com/photo-1540039155733-5bb30b53aa14?w=800',
    },
    {
      'title': 'Book in Seconds',
      'description': 'Fast, secure checkout with multiple payment options. Your tickets, your way.',
      'image': 'https://images.unsplash.com/photo-1501281668745-f7f57925c3b4?w=800',
    },
  ];

  // ─── CITIES ────────────────────────────────────────────
  static const List<String> cities = [
    'All Cities',
    'New York',
    'London',
    'Los Angeles',
    'Sydney',
    'Denver',
    'Las Vegas',
    'Indio',
  ];

  // ─── TAKEN SEATS (pre-occupied for seat selection) ─────
  static const List<String> takenSeats = [
    'A1', 'A2', 'A7', 'A8',
    'B3', 'B4', 'B9',
    'C1', 'C5', 'C6', 'C10',
    'D2', 'D7', 'D8', 'D9',
    'E3', 'E4', 'E5',
    'F1', 'F6', 'F10',
    'G2', 'G8', 'G9',
    'H1', 'H5', 'H6', 'H10',
  ];

  static const List<String> vipSeats = [
    'A3', 'A4', 'A5', 'A6',
    'B1', 'B2', 'B5', 'B6', 'B7', 'B8',
  ];
}
